server:
  port: 80
  servlet:
    context-path: /reborn_new_life
    session:
      timeout: 120m
  tomcat:
    threads:
      min-spare: 5
      max: 10
    max-connections: 15
    accept-count: 10  
   
spring:
  session:
    jdbc:
      table-name: SPRING_SESSION
      #initialize-schema: always #產spring session schema
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver 
      url: jdbc:mysql://aws-first-database.ckkpuswf8ke8.ap-southeast-2.rds.amazonaws.com:3306/new_shopping?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&useSSL=false
      username: admin
      password: mm12583$
      # 連線池大小
      initial-size: 2
      min-idle: 2
      max-active: 5
      max-wait: 2000
      # 檢測連接是否還有效
      timeBetweenEvictionRunsMillis: 120000
      validationQuery: SELECT 1  # MySQL 新版用ping 檢測
      testWhileIdle: true # 定期
      testOnBorrow: false # 獲取連線時
      testOnReturn: false # 歸還時
      # PSCache
      poolPreparedStatements: true
      filter:
        slf4j:
          enabled: true
        wall:
          enabled: true
        stat:
          enabled: true
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      web-stat-filter:
        enabled: true
        url-pattern: "/*"
        exclusions: "*.js,*.gif,*.jpg,*.bmp,*.png,*.css,*.ico,/druid/*"
      stat-view-servlet:
        enabled: true
        url-pattern: "/druid/*"
        # IP白名單
        # allow: 
        # IP白名單 
        # deny: 
        reset-enable: false #禁用 Html reset
        login-username: newlife
        login-password: 12345
  jpa:
    show-sql: false
    open-in-view: false
    hibernate:
      ddl-auto: none
  devtools:
    restart:
      enabled: false

logging:
  config: classpath:logback-spring.xml
  level:
    entitySQL: info
    baseController: info
  group:
    # controller
    baseController: com.reborn.newlife.home.controller
    # database SQL
    entitySQL: com.reborn.newlife.XXX.entity
    
    
    
    
    
    
    
    
    
    
    
    
    
    