#啟動環境
spring:
  profiles:
    active: dev
  mvc:    pathmatch:      matching-strategy: ant-path-matcher
  banner:
    charset: UTF-8
    location: classpath:banner.txt  
  
logging:  pattern:    console: "%date{yyyy-MM-dd HH:mm:ss} -%5level [%15.15thread] %-40.40logger{39} : %msg%n"
      
    
    
    
    
    
    
    
    
    
    
    
    
    
    