#啟動環境
spring:
  profiles:
    active: dev
  mvc:    pathmatch:      matching-strategy: ant-path-matcher
  banner:
    charset: UTF-8
    location: classpath:banner.txt  
  

      
    
    
    
    
    
    
    
    
    
    
    
    
    
    